### ISSUE TITLE
The add-on keeps updating

### ISSUE THREAD

**Issue by Mornon** [Arthur-Milchior/Anki-postpone-reviews#23]
Since last update, when I open Anki I get an update for this addon: not each time I open it, but since the last update (marked on 29/01 on the site) I got the update notification at least six times, I think more.

I already tried to uninstall and reinstall it, to no avail, I got asked to update it at least a couple of times.

**Comment by AnKingMed** [comment]
I have the same issue

**Comment by Arthur-Milchior** [comment]
Hi,

Thanks for the report.
I can imagine how frustrating it is, sorry.
I tried to reupload it, let me know if it solve the problem. I've no idea what may be going on.

Which version of anki do you use?

**Comment by AnKingMed** [comment]
I've tried on .38 and .41beta   It's still saying it needs to update any time I check for updates

**Comment by Mornon** [comment]
It's not a big issue, don't worry, I was reporting it mainly because I don't know if it hints at some other issue.

I'm using Anki ⁨2.1.38⁩; at the moment it updated again one time, but after closing it if I check for updates manually it doesn't find anything new. I'll wait and see if it updates automatically when I open Anki in the next days and keep you updated, thanks for your reply.

**Comment by AnKingMed** [comment]
Update: I updated one last time and now the issue seems to be resolved

**Comment by Arthur-Milchior** [comment]
I am going to disagree with you. This add-on was downloaded 46729 times. I don't know how many people still use it today, because I literally have not any statistic more detailled, but at least thousands of people is realistic. Annoying so many people is not a small issue, at least if it's easy to fix. 
If it didn't work, I would have asked Damien's help. But if it works, great.

Thanks for the report, 
If after a few other open/close it works, please think abotu closing the ticket
