### ISSUE TITLE
Reset back?

### ISSUE THREAD

**Issue by TCV21** [Arthur-Milchior/Anki-postpone-reviews#8]
Hey, so I think I kinda shot myself in the foot because I was playing around with the delays on my deck and now my intervals are set to ridiculous intervals that went from the default to 3, 5, 10 months and when I add/subtract days these intervals change between weeks to years..

Is there anyway that the add-ons effects on my settings can be reversed?

**Comment by Arthur-Milchior** [comment]
If it's recent, my best advice is as follow:
* copy the back-up folder (so you're sure to keep current backup and not overriding them)
* try to open a recent backup, dating from before you did shot yourself in the foot.
If you use anki on any other computer which is not yet sinced, it may be a good way to have the data.



If you know exactly how much day you did add/remove each time, and when you did that, it may be theoretically possible - but complex - to mathematically compute the original dates. Otherwise, the data is not saved anywhere as far as I know. 

What do you call «the default» when you speak of interval. Because honestly, 10 months is not absurd at all, especially for cards which are easy and you've seen multiple times in the past monthes.
Normally, the add-on would not change "1 day" to "10 monthes" unless you postpone everything by monthes.
